- name: "Require sudo password for '{{ user_or_group_str }}' auth: {{ not set_nopassword_auth }}"
  set_fact:
    nopassword_opt: "{{ 'NOPASSWORD: ' if set_nopassword_auth else '' }}"
  when: set_nopassword_auth is defined

- name: "Limit '{{ user_or_group_str }}' auth to list of commands"
  set_fact:
    allowed_cmds: "{{ auth_cmd_list | join(',') }}"
  when: auth_cmd_list is defined

- name: "Set '{{ user_or_group_str }}' full/limited auth"
  include_tasks: func/edit_sudoers_opt.yml
  vars:
    task_name: "Set full/limited auth for '{{ user_or_group_str }}"
    task_regexp: >-
      ^#?\s*{{ user_or_group_str }} \w+=
    task_line: >-
      {{ user_or_group_str }} ALL=(ALL) {{ nopassword_opt }}{{ allowed_cmds | default('ALL') }}

