- name: "Set full auth for group '{{ sudo_users_group }}' in {{ sudoers_file }}"
  lineinfile:
    path: "{{ sudoers_file }}"
    regexp: >-
      ^#?\s*%{{ sudo_users_group }} \w+=
    line: >-
      %{{ sudo_users_group }} ALL=(ALL) ALL
    validate: >-
      visudo --check --file=%s
    firstmatch: yes
    state: present
  become: true
  become_user: root

