- name: "Set password-prompt timeout"
  include_tasks: func/edit_sudoers_opt.yml
  vars:
    description: "set timeout-quit after asking for password"
    config_lines: >-
      Defaults passwd_timeout={{ password_prompt_timeout_minutes }}

