- name: "Set group auth"
  include_tasks: edit_sudoers_opt.yml
  vars:
    task_name: "Set full auth for group '{{ sudo_users_group }}"
    task_regexp: >-
      ^#?\s*%{{ sudo_users_group }} \w+=
    task_line: >-
      %{{ sudo_users_group }} ALL=(ALL) ALL

