- name: "Set full auth for group '{{ config_sudo_group }}' in {{ config_sudo_sudoers_file }}"
  lineinfile:
    path: "{{ config_sudo_sudoers_file }}"
    regexp: >-
      ^#?\s*%{{ config_sudo_group }} \w+=
    line: >-
      %{{ config_sudo_group }} ALL=(ALL) ALL
    validate: >-
      visudo --check --file=%s
    state: present
  become: true
  become_user: root

