- name: "Set group auth"
  include_tasks: edit_sudoers_opt.yml
  vars:
    task_name: "Set full auth for group '{{ set_auth_for_group }}"
    task_regexp: >-
      ^#?\s*%{{ set_auth_for_group }} \w+=
    task_line: >-
      %{{ set_auth_for_group }} ALL=(ALL) ALL

