- name: "Run all roles defined as dependencies"
  include_tasks: run_dep_roles.yml

- name: "Install sudo utility"
  include_tasks: install_sudo.yml

# - name: "Grant full sudo authority for user 'root'"
#   include_tasks: config_root_auth.yml

- name: "Grant full sudo authority for group '{{ sudo_users_group }}'"
  include_tasks: config_group_auth.yml
  when: sudo_users_group is defined

- name: "Set wait between sudo ask-password events"
  include_tasks: config_ask_pswd.yml
  when: ask_password_timeout is defined

- name: "Set number of minutes to timeout, when waiting for sudo password"
  include_tasks: config_pswd_prompt.yml
  when: password_prompt_timeout_minutes is defined

- name: "Use root-user umask for file creation (not user's umask)"
  include_tasks: set_root_umask.yml
  when: use_root_umask is defined

