- name: "Install sudo utility"
  include_tasks: install_sudo.yml

- name: "Grant full sudo authority for user 'root'"
  include_tasks: config_root_auth.yml
  when: set_full_root_authority

- name: "Grant full sudo authority for group '{{ sudo_users_group }}'"
  include_tasks: config_group_auth.yml
  when: sudo_users_group is defined

- name: "Set wait between sudo ask-password events"
  include_tasks: config_ask_pswd.yml

- name: "Disable password prompt timeout"
  include_tasks: config_pswd_prompt.yml
  when: disable_password_prompt_timeout

