- name: "Run config-shell role as dependency"
  include_role:
    name: ans-role-config-shell
  vars:
    user_name: "{{ user_for_sudo_customization }}"
  when: user_for_sudo_customization is defined

